//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&NodeQOSEnsurancePolicy{}, func(obj interface{}) { SetObjectDefaults_NodeQOSEnsurancePolicy(obj.(*NodeQOSEnsurancePolicy)) })
	return nil
}

func SetObjectDefaults_NodeQOSEnsurancePolicy(in *NodeQOSEnsurancePolicy) {
	SetDefaults_NodeQOSEnsurancePolicy(in)
	for i := range in.Spec.ObjectiveEnsurances {
		a := &in.Spec.ObjectiveEnsurances[i]
		SetDefaults_ObjectiveEnsurance(a)
	}
}
